In [32]:
import pandas as pd
import os

In [33]:
data_folder = '../data/'
all_dataframes = []

#create the good colum names
column_names = [
    'Link no', 'Name',
    'Start_LRP', 'Start_Offset', 'Start_Chainage',
    'End_LRP', 'End_Offset', 'End_Chainage',
    'Length_Km', 'Heavy_Truck', 'Medium_Truck', 'Small_Truck',
    'Large_Bus', 'Medium_Bus', 'Micro_Bus', 'Utility',
    'Car', 'Auto_Rickshaw', 'Motor_Cycle', 'Bi_Cycle',
    'Cycle_Rickshaw', 'Cart', 'Motorized', 'Non_Motorized', 'Total_AADT'
]

for filename in os.listdir(data_folder):
    if filename.endswith(".traffic.htm"):
        file_path = os.path.join(data_folder, filename)
        tables = pd.read_html(file_path, encoding='ISO-8859-1')
        if len(tables) > 0:
            #get the last table, and we only need the first 25 columns.
            df = tables[-1].iloc[:, :25]

            #skip the first three lines with html, and get the real data
            df = df.iloc[3:].copy()

            #make it the right column names
            df.columns = column_names

            #add the road
            df['Road'] = filename.split('.')[0]

            all_dataframes.append(df)

#put all together
final_df = pd.concat(all_dataframes, ignore_index=True)

#road is final column
cols = ['Road'] + [c for c in final_df.columns if c != 'Road']
final_df = final_df[cols]

# Toon het resultaat
display(final_df.head())

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Utility,Car,Auto_Rickshaw,Motor_Cycle,Bi_Cycle,Cycle_Rickshaw,Cart,Motorized,Non_Motorized,Total_AADT
0,N1,N1-1L,Jatrabari - Int.with Z1101 (Left) (Left),LRPS,0,0,LRPS,822,0.822,0.822,...,238.0,1851.0,2980.0,398.0,232.0,889.0,0.0,18236.0,1121.0,19357.0
1,N1,N1-1R,Jatrabari - Int.with Z1101 (Left) (Right),LRPS,0,0,LRPS,822,0.822,0.822,...,480.0,2608.0,2508.0,436.0,213.0,1088.0,0.0,20236.0,1301.0,21537.0
2,N1,N1-2L,Int.with Z1101 - Signboard (Left) R111 (Left),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,480.0,2608.0,2508.0,436.0,213.0,1088.0,0.0,20236.0,1301.0,21537.0
3,N1,N1-2R,Int.with Z1101 - Signboard (Left) R111 (Right),LRPS,822,0.822,LRPS,4175,4.175,3.353,...,238.0,1851.0,2980.0,398.0,232.0,889.0,0.0,18236.0,1121.0,19357.0
4,N1,N1-3L,Signboard - Shimrail (Left)R110 (Left),LRPS,4175,4.175,LRPS,7181,7.181,3.006,...,314.0,1690.0,2266.0,1087.0,75.0,1198.0,0.0,16288.0,1273.0,17561.0

In [34]:
display(final_df.tail())

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Utility,Car,Auto_Rickshaw,Motor_Cycle,Bi_Cycle,Cycle_Rickshaw,Cart,Motorized,Non_Motorized,Total_AADT
177,N208,N208-1,Moulvibazar-Int.with Z2002,LRPS,0,0,LRPS,3190,3.19,3.190,...,149.0,741.0,3194.0,1123.0,147.0,486.0,0.0,7514.0,633.0,8147.0
178,N208,N208-2,Int.with Z2002-Rajnagar (Int.with R281),LRPS,3190,3.19,LRP012,1661,13.461,10.271,...,149.0,741.0,3194.0,1123.0,147.0,486.0,0.0,7514.0,633.0,8147.0
179,N208,N208-3,Rajnagar(Int.with R281)-Daudabad (Int.with Z2832),LRP012,1661,13.461,LRP052,385,51.05,37.589,...,78.0,811.0,2233.0,582.0,88.0,73.0,0.0,5328.0,161.0,5489.0
180,N208,N208-4,Daudabad (Int.with Z2832)-Royal City Chottor(i...,LRP052,385,51.05,LRP054,677,53.342,2.292,...,78.0,811.0,2233.0,582.0,88.0,73.0,0.0,5328.0,161.0,5489.0
181,N208,N208-5,Royal City Chottor(int.with N210)-Int.with N2,LRP054,677,53.342,LRP058,900,57.495,4.153,...,77.0,778.0,2974.0,1231.0,695.0,822.0,47.0,9488.0,1564.0,11052.0

In [36]:
#check for example the N106
n106_data = final_df[final_df['Road'] == 'N106']
display(n106_data)

,Road,Link no,Name,Start_LRP,Start_Offset,Start_Chainage,End_LRP,End_Offset,End_Chainage,Length_Km,...,Utility,Car,Auto_Rickshaw,Motor_Cycle,Bi_Cycle,Cycle_Rickshaw,Cart,Motorized,Non_Motorized,Total_AADT
133,N106,N106-1,Chittagong (Oxygen More)-Hathazari (Int. with ...,LRPS,0,0,LRP010,2084,12.192,12.192,...,289.0,1063.0,8817.0,1355.0,234.0,393.0,0.0,17165.0,627.0,17792.0
134,N106,N106-2,Hathazari (Int. with R160)-Gohira(Int.with Z1619),LRP010,2084,12.192,LRP018,1533,19.321,7.129,...,217.0,296.0,5481.0,1078.0,576.0,943.0,0.0,8908.0,1519.0,10427.0
135,N106,N106-3,Gohira(Int.with Z1619)-Munshihat (Int.with Z1629),LRP018,1533,19.321,LRP024,828,24.297,4.976,...,217.0,296.0,5481.0,1078.0,576.0,943.0,0.0,8908.0,1519.0,10427.0
136,N106,N106-4,Munshihat (Int.with Z1629)-Raozan (Int.with Z1...,LRP024,828,24.297,LRP025,820,25.278,0.981,...,217.0,296.0,5481.0,1078.0,576.0,943.0,0.0,8908.0,1519.0,10427.0
137,N106,N106-5,Raozan (Int.with Z1012)-Ranirhat (Int.with Z1613),LRP025,820,25.278,LRP039,690,37.25,11.972,...,418.0,103.0,520.0,372.0,0.0,0.0,0.0,2443.0,0.0,2443.0
138,N106,N106-6,Ranirhat (Int.with Z1613)-Gabtoli (Int.with Z1...,LRP039,690,37.25,LRP044,296,41.825,4.575,...,418.0,103.0,520.0,372.0,0.0,0.0,0.0,2443.0,0.0,2443.0
139,N106,N106-7,Gabtoli (Int.with Z1617)-Ghagra (Int. with R161),LRP044,296,41.825,LRP051,147,48.879,7.054,...,418.0,103.0,520.0,372.0,0.0,0.0,0.0,2443.0,0.0,2443.0
140,N106,N106-8,Ghagra (Int. with R161)-Manikchhari(Int. with ...,LRP051,147,48.879,LRP059,566,57.303,8.424,...,83.0,35.0,904.0,471.0,0.0,0.0,0.0,1975.0,0.0,1975.0
141,N106,N106-9,Manikchhari(Int. with R162)-Rangamati,LRP059,566,57.303,LRPE,0,66.85,9.547,...,83.0,35.0,904.0,471.0,0.0,0.0,0.0,1975.0,0.0,1975.0