In [10]:
import pandas as pd

In [11]:
import os
print(os.getcwd())  # Shows current working directory

c:\Users\lieke\OneDrive\Documents\TU Delft\EPA\Q3 - 2025\Advanced Simulation\Project Files\Project\EPA133A-Advanced-Simulation-Group-1\Assignment 1\EPA133a-G01-A1\notebook

In [12]:
df_bridges = pd.read_excel('../data/raw/BMMS_overview.xlsx')

In [13]:
df_bridges.head(10)

,road,km,type,LRPName,name,length,condition,structureNr,roadName,chainage,width,constructionYear,spans,zone,circle,division,sub-division,lat,lon,EstimatedLoc
0,N1,1.800,Box Culvert,LRP001a,.,11.30,A,117861,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,1.8,19.50,2005.0,2.0,Dhaka,Dhaka,Narayanganj,Narayanganj-1,23.702889,90.450389,bcs1
1,N1,4.925,Box Culvert,LRP004b,.,6.60,A,117862,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,4.925,35.40,2006.0,1.0,Dhaka,Dhaka,Narayanganj,Narayanganj-1,23.693611,90.478833,bcs1
2,N1,8.976,PC Girder Bridge,LRP008b,Kanch pur Bridge.,394.23,A,119889,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,8.976,NaN,NaN,NaN,Dhaka,Dhaka,Narayanganj,Narayanganj-1,23.704583,90.518833,road_precise
3,N1,10.880,Box Culvert,LRP010b,NOYAPARA CULVERT,6.30,A,112531,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,10.88,12.20,1992.0,2.0,Dhaka,Dhaka,Narayanganj,Vitikandi,23.699833,90.530722,bcs1
4,N1,10.897,Box Culvert,LRP010c,ADUPUR CULVERT,6.30,A,112532,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,10.897,12.20,1984.0,2.0,Dhaka,Dhaka,Narayanganj,Vitikandi,23.699667,90.530722,bcs1
5,N1,11.296,Box Culvert,LRP011a,NAYABARI KASPUR BOX CULVERT,8.30,A,101110,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,11.296,21.45,1986.0,2.0,Dhaka,Dhaka,Narayanganj,Vitikandi,23.697361,90.533833,bcs1
6,N1,12.239,Box Culvert,LRP012a,KHAS PARA BOX CULVERT,9.30,A,101117,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,12.239,21.00,1986.0,2.0,Dhaka,Dhaka,Narayanganj,Vitikandi,23.692333,90.541000,bcs1
7,N1,12.253,Box Culvert,LRP012b,DAWAN BAG BOX CULVERT,6.10,A,101119,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,12.253,20.60,1987.0,2.0,Dhaka,Dhaka,Narayanganj,Vitikandi,23.692556,90.541139,bcs1
8,N1,12.660,PC Girder Bridge,LRP013a,Madanpur Bridge.(L),27.50,A,119897,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,12.66,NaN,NaN,NaN,Dhaka,Dhaka,Narayanganj,Vitikandi,23.685500,90.551278,road_precise
9,N1,12.660,PC Girder Bridge,LRP013a,MADAN PUR (R),26.30,A,109841,Dhaka (Jatrabari)-Comilla (Mainamati)-Chittago...,12.66,9.20,2003.0,1.0,Dhaka,Dhaka,Narayanganj,Vitikandi,23.691111,90.544889,bcs1

In [14]:
df_bridges.info()
df_bridges.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21407 entries, 0 to 21406
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   road              21407 non-null  object
 1   km                21406 non-null  float64
 2   type              21407 non-null  object
 3   LRPName           21407 non-null  object
 4   name              21060 non-null  object
 5   length            21398 non-null  float64
 6   condition         21407 non-null  object
 7   structureNr       21407 non-null  int64
 8   roadName          21406 non-null  object
 9   chainage          21407 non-null  object
 10  width             18290 non-null  float64
 11  constructionYear  18289 non-null  float64
 12  spans             18290 non-null  float64
 13  zone              21406 non-null  object
 14  circle            21406 non-null  object
 15  division          21406 non-null  object
 16  sub-division      21406 non-null  object
 17  lat               21313 non-null  float64
 18  lon               21313 non-null  float64
 19  EstimatedLoc      21407 non-null  object
dtypes: float64(7), int64(1), object(12)
memory usage: 3.3+ MB

,km,length,structureNr,width,constructionYear,spans,lat,lon
count,21406.000000,21398.00000,21407.000000,18290.000000,18289.000000,18290.000000,21313.000000,21313.000000
mean,41.217405,16.62539,110961.360676,7.813633,1990.171961,1.465500,23.828505,90.227328
std,78.810955,43.85946,6319.200562,6.193465,10.123705,1.179609,2.247895,3.364169
min,0.000000,0.20000,100001.000000,1.380000,1942.000000,1.000000,0.000000,0.000000
25%,6.207250,2.68000,105466.500000,5.000000,1985.000000,1.000000,22.942527,89.377806
50%,15.147000,5.60000,110978.000000,7.300000,1992.000000,1.000000,23.823743,90.289194
75%,35.012250,15.80000,116441.500000,9.700000,1998.000000,1.000000,24.720939,91.288417
max,522.718000,1786.00000,121862.000000,702.000000,2013.000000,31.000000,91.544194,93.298416

In [15]:
print(df_bridges['type'].value_counts())
print(df_bridges['EstimatedLoc'].value_counts())

type
Box Culvert               9427
RCC Girder Bridge         4057
Slab Culvert              3978
Baily with Steel Deck     1431
PC Girder Bridge           894
Truss with Steel Deck      530
Steel Beam & RCC Slab      332
RCC Bridge                 319
Arch Masonry               317
Truss with RCC Slab         68
Baily with Timber Deck      36
PC Box                       9
Truss With Timber Deck       8
Pipe Culvert                 1
Name: count, dtype: int64
EstimatedLoc
bcs1                18352
road_precise         2301
road_interpolate      640
road_chainage          82
error                  31
bcs1_zerosec            1
Name: count, dtype: int64

**BRUGGEN**
1. Een brug moet op een weg liggen
2. Een brug ligt afhankelijk van het type wel of niet over het water.
3. Een brug is ook een LRP op een weg, deze kun je matchen
4. Een brug moet binnen de landsgrensen van Bangladesh liggen

## Matching bridges to roads
Bepaal voor elke brug: welk punt op welke weg en wat zijn de coördinaten

In [19]:
#grenzen voor Bangladesh
lat_min, lat_max = 20.0, 27.0
lon_min, lon_max = 88.0, 93.0

df_bridges['is_outlier'] = (
    (df_bridges['lat'] < lat_min) | (df_bridges['lat'] > lat_max) |
    (df_bridges['lon'] < lon_min) | (df_bridges['lon'] > lon_max)
)

print(f"Aantal bruggen met verdachte locaties: {df_bridges['is_outlier'].sum()}")

df_outliers = df_bridges[df_bridges['is_outlier'] == True]
display(df_outliers)

Aantal bruggen met verdachte locaties: 43

,road,km,type,LRPName,name,length,condition,structureNr,roadName,chainage,...,constructionYear,spans,zone,circle,division,sub-division,lat,lon,EstimatedLoc,is_outlier
2864,R241,29.840,Box Culvert,LRP029a,MAJIDEPUR BOX CULVERT,3.00,A,114991,Auskandi-Raniganj-Jagannathpur-Pagla Road,29.84,...,1992.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.543889,24.805111,bcs1,True
2865,R241,31.212,Baily with Steel Deck,LRP031a,KHASIRA BAILEY WITH STEEL DECK,17.50,A,114990,Auskandi-Raniganj-Jagannathpur-Pagla Road,31.212,...,1992.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.538722,24.816556,bcs1,True
2866,R241,32.713,Box Culvert,LRP032b,KOLKALI BOX CULVERT,3.00,A,114988,Auskandi-Raniganj-Jagannathpur-Pagla Road,32.713,...,1997.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.530556,24.828056,bcs1,True
2867,R241,33.126,Box Culvert,LRP033a,KOKAL BOX CULVERT,1.00,A,114987,Auskandi-Raniganj-Jagannathpur-Pagla Road,33.126,...,1996.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.527917,24.830944,bcs1,True
2868,R241,34.978,Box Culvert,LRP035a,TARAKHAI BOX CULVERT,14.40,A,114984,Auskandi-Raniganj-Jagannathpur-Pagla Road,34.978,...,1985.0,3.0,Sylhet,Sylhet,Sunamganj,Chattak,91.518194,24.844972,bcs1,True
2869,R241,36.164,Truss with Steel Deck,LRP036a,COUNDER NOLA BRIDGE,40.60,A,114982,Auskandi-Raniganj-Jagannathpur-Pagla Road,36.164,...,1984.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.514083,24.855083,bcs1,True
6681,Z1405,51.682,Truss with Steel Deck,LRP054a,Ajadnagar Bridge,81.51,A,121419,Lakshmipur-Char Alaxandar-Sonapur Road,51.682,...,NaN,NaN,Comilla,Noakhali,Laxmipur,Laxmipur,0.000000,0.000000,road_precise,True
7456,Z1811,147.040,Baily with Steel Deck,LRP149a,Tulatoli Bridge,24.15,A,121607,Bandarban-Chimbuk-Thanchi-Alikadam-Baisari-Nai...,147.04,...,NaN,NaN,Chittagong,Rangamati,Bandarban,Bandarban-1,0.000000,0.000000,road_interpolate,True
7458,Z1811,147.506,RCC Girder Bridge,LRP149d,Naikhongchari Bazar Bridge.,12.50,A,121608,Bandarban-Chimbuk-Thanchi-Alikadam-Baisari-Nai...,147.506,...,NaN,NaN,Chittagong,Rangamati,Bandarban,Bandarban-1,0.000000,0.000000,road_interpolate,True
7462,Z1811,149.145,RCC Girder Bridge,LRP151a,South Bisamara Bridge,6.80,A,121620,Bandarban-Chimbuk-Thanchi-Alikadam-Baisari-Nai...,149.145,...,NaN,NaN,Chittagong,Rangamati,Bandarban,Bandarban-1,0.000000,0.000000,road_interpolate,True
7540,Z1813,12.236,Baily with Steel Deck,LRP013c,Rolingpara bridge-3,24.44,A,121660,Bandarban-Rowangchhari-Ruma Road,12.236,...,NaN,NaN,Chittagong,Rangamati,Bandarban,Bandarban-2,22.197833,93.298416,road_precise,True
12415,Z2813,11.630,PC Girder Bridge,LRP011a,Barohal Bridge,60.00,B,121517,Sunamganj-Tekerhat-Badaghat-Tahirpur Road,11.63,...,NaN,NaN,Sylhet,Sylhet,Sunamganj,Sunamganj,0.000000,0.000000,road_interpolate,True
12417,Z2813,18.250,RCC Bridge,LRP018a,Pahartali Bridge,18.00,B,120087,Sunamganj-Tekerhat-Badaghat-Tahirpur Road,18.25,...,NaN,NaN,Sylhet,Sylhet,Sunamganj,Sunamganj,0.000000,0.000000,road_interpolate,True
12418,Z2813,24.510,RCC Bridge,LRP024c,Jamalgar Bridge,15.00,B,121521,Sunamganj-Tekerhat-Badaghat-Tahirpur Road,24.51,...,NaN,NaN,Sylhet,Sylhet,Sunamganj,Sunamganj,0.000000,0.000000,road_interpolate,True
13368,Z8203,0.193,Baily with Steel Deck,LRPSa,Hasara Bridge,24.60,B,120357,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,0.193,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,19.098529,72.877077,road_interpolate,True
13369,Z8203,2.573,Baily with Steel Deck,LRP002a,Buichid Bridge,24.70,B,120349,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,2.573,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,0.000000,0.000000,road_interpolate,True
14794,Z8203,3.492,Truss with Steel Deck,LRP003a,Kathalbari Bridge,36.70,A,120350,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,3.492,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,0.000000,0.000000,road_interpolate,True
14795,Z8203,3.930,Truss with Steel Deck,LRP003c,Birtara Bridge,31.20,A,120353,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,3.93,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,0.000000,0.000000,road_interpolate,True
14796,Z8203,5.665,Truss with Steel Deck,LRP005a,Beltoli Bridge,36.80,A,120355,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,5.665,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,0.000000,0.000000,road_interpolate,True
16183,R241,26.292,Box Culvert,LRP026a,EKOR CHOL BOX CULVERT,12.00,B,114995,Auskandi-Raniganj-Jagannathpur-Pagla Road,26.292,...,1992.0,5.0,Sylhet,Sylhet,Sunamganj,Chattak,91.544194,24.773694,bcs1,True
16185,R241,28.857,Baily with Steel Deck,LRP028c,MAJIDPUR TRUSS BRIDGE,37.90,B,114992,Auskandi-Raniganj-Jagannathpur-Pagla Road,28.857,...,1992.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.542083,24.796694,bcs1,True
17247,R241,28.211,Box Culvert,LRP028a,HIJLA BOX CULVERT,9.20,C,114993,Auskandi-Raniganj-Jagannathpur-Pagla Road,28.211,...,1992.0,2.0,Sylhet,Sylhet,Sunamganj,Chattak,91.541778,24.790944,bcs1,True
17248,R241,32.128,Box Culvert,LRP032a,KHASIRA BOX CULVERT,6.00,C,114989,Auskandi-Raniganj-Jagannathpur-Pagla Road,32.128,...,1992.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.534361,24.823833,bcs1,True
17249,R241,33.759,Baily with Steel Deck,LRP033b,GONGUR BAILEY WITH STEEL DECK,14.20,C,114986,Auskandi-Raniganj-Jagannathpur-Pagla Road,33.759,...,1998.0,1.0,Sylhet,Sylhet,Sunamganj,Chattak,91.524083,24.835222,bcs1,True
17251,R241,34.785,Truss with Steel Deck,LRP034a,TARA KHAI BRIDGE,57.20,C,114985,Auskandi-Raniganj-Jagannathpur-Pagla Road,34.785,...,1992.0,2.0,Sylhet,Sylhet,Sunamganj,Chattak,91.519389,24.842889,bcs1,True
17252,R241,35.575,Box Culvert,LRP035c,COUNDER NOLA BOX CULVERT,14.40,C,114983,Auskandi-Raniganj-Jagannathpur-Pagla Road,35.575,...,2003.0,3.0,Sylhet,Sylhet,Sunamganj,Chattak,91.516167,24.849861,bcs1,True
17254,R241,38.340,RCC Girder Bridge,LRP038a,BOMBOMI BRIDGE,45.20,C,114981,Auskandi-Raniganj-Jagannathpur-Pagla Road,38.34,...,1964.0,3.0,Sylhet,Sylhet,Sunamganj,Chattak,91.500417,24.867917,bcs1,True
18641,Z1811,148.667,Baily with Timber Deck,LRP150b,Uttor Bisamara Bridge,15.60,C,121612,Bandarban-Chimbuk-Thanchi-Alikadam-Baisari-Nai...,148.667,...,NaN,NaN,Chittagong,Rangamati,Bandarban,Bandarban-1,0.000000,0.000000,road_interpolate,True
18752,Z2812,10.450,RCC Girder Bridge,LRP010a,NaN,40.00,C,121854,Beanibazar (Bairagirbazar)-Kurerbazar-Budbarib...,10.45,...,NaN,NaN,Sylhet,Sylhet,Sylhet,Golapganj,22.015527,81.616806,road_interpolate,True
18754,Z2812,23.430,RCC Girder Bridge,LRP023a,NaN,13.00,C,121855,Beanibazar (Bairagirbazar)-Kurerbazar-Budbarib...,23.43,...,NaN,NaN,Sylhet,Sylhet,Sylhet,Golapganj,15.137993,56.120148,road_interpolate,True
18755,Z2812,24.150,RCC Girder Bridge,LRP024a,NaN,20.00,C,121857,Beanibazar (Bairagirbazar)-Kurerbazar-Budbarib...,24.15,...,NaN,NaN,Sylhet,Sylhet,Sylhet,Golapganj,14.756497,54.705849,road_interpolate,True
18756,Z2812,26.740,RCC Girder Bridge,LRP026d,NaN,21.00,C,121858,Beanibazar (Bairagirbazar)-Kurerbazar-Budbarib...,26.74,...,NaN,NaN,Sylhet,Sylhet,Sylhet,Golapganj,13.384169,49.618304,road_interpolate,True
18757,Z2812,29.130,RCC Girder Bridge,LRP029b,NaN,10.00,C,121860,Beanibazar (Bairagirbazar)-Kurerbazar-Budbarib...,29.13,...,NaN,NaN,Sylhet,Sylhet,Sylhet,Golapganj,12.117812,44.923618,road_interpolate,True
18758,Z2812,29.820,RCC Girder Bridge,LRP029f,NaN,20.00,C,121861,Beanibazar (Bairagirbazar)-Kurerbazar-Budbarib...,29.82,...,NaN,NaN,Sylhet,Sylhet,Sylhet,Golapganj,11.752212,43.568249,road_interpolate,True
18759,Z2812,30.070,RCC Girder Bridge,LRP030a,NaN,12.00,C,121862,Beanibazar (Bairagirbazar)-Kurerbazar-Budbarib...,30.07,...,NaN,NaN,Sylhet,Sylhet,Sylhet,Golapganj,11.619748,43.077173,road_interpolate,True
18761,Z2813,12.710,RCC Girder Bridge,LRP012b,Gutila Bridge,18.70,C,121520,Sunamganj-Tekerhat-Badaghat-Tahirpur Road,12.71,...,NaN,NaN,Sylhet,Sylhet,Sunamganj,Sunamganj,0.000000,0.000000,road_interpolate,True
20113,Z8203,1.749,Baily with Steel Deck,LRP001c,Satgaon Bridge,27.60,C,120347,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,1.749,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,0.000000,0.000000,road_interpolate,True
20114,Z8203,4.717,Baily with Steel Deck,LRP004a,Tingaon Bridge,18.50,C,120354,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,4.717,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,0.000000,0.000000,road_interpolate,True
20439,R171,14.759,Slab Culvert,LRP014b,Adorshopara,7.60,D,113882,Banshkhali (Charati)-Chunti Road,14.759,...,1992.0,1.0,Chittagong,Chittagong,Dohazari,Dohazari,27.980972,92.065611,bcs1,True
20460,R241,27.743,Box Culvert,LRP027a,EKOR CHAI BOX CULVERT,19.90,D,114994,Auskandi-Raniganj-Jagannathpur-Pagla Road,27.743,...,2001.0,3.0,Sylhet,Sylhet,Sunamganj,Chattak,91.542389,24.786833,bcs1,True
21281,Z7602,12.072,RCC Girder Bridge,LRP013b,Kalia bridge,56.80,D,119058,Satkhira-Shakhipur-Kaliganj Road,12.072,...,NaN,NaN,Khulna,Khulna,Satkhira,Satkhira-2,15.869151,88.989909,road_interpolate,True
21309,Z7718,38.930,RCC Girder Bridge,LRP038a,Mithakali bridge,19.90,D,119191,Kachua (Pingoria)-Talighati-Herma-Rampal Road,38.93,...,NaN,NaN,Khulna,Khulna,Bagerhat,Bagerhat-2,0.000000,0.000000,road_interpolate,True
21362,Z8203,1.192,Baily with Steel Deck,LRP001a,Hasara Bridge (East),24.00,D,120345,Keraniganj (Sayedpur)-Hashara-Birtara-Singpara...,1.192,...,NaN,NaN,Dhaka,Dhaka,Munshiganj,Keraniganj,0.000000,0.000000,road_interpolate,True