In [1]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.read_csv('../data/_roads3.csv')
# print(df1.head())

dfN1 = df1[df1['road'] == 'N1']

In [5]:
source_val = 0
sink_val = dfN1['chainage'].max()
source_row = dfN1[dfN1['chainage'] == source_val].head(1)
sink_row = dfN1[dfN1['chainage'] == sink_val].head(1)

In [8]:
df_proc = pd.concat([source_row, sink_row]).drop_duplicates(subset=['chainage', 'lrp']).sort_values('chainage').reset_index(drop=True)

In [10]:
df_proc.head(10)

,road,chainage,lrp,lat,lon,gap,type,name
0,N1,0.000,LRPS,23.706028,90.443333,NaN,Others,Start of Road after Jatrabari Flyover infront...
1,N1,462.254,LRPE,20.862917,92.298083,NaN,Others,"End of Road at Shapla Chattar ,Teknaf Meet wit..."

In [11]:
df_BMMS = pd.read_excel('../data/BMMS_overview.xlsx')

In [15]:
cols = [
    "road",
    "name",
    "length",
    "chainage",
    "lat",
    "lon",
    "condition",
]

bridges_BMMS = df_BMMS[cols].copy()

In [18]:
bridges_BMMS.head(20)

,road,name,length,chainage,lat,lon,condition
0,N1,.,11.30,1.800,23.698739,90.458861,A
1,N1,.,6.60,4.925,23.694664,90.487775,A
2,N1,Kanch pur Bridge.,394.23,8.976,23.705060,90.523214,A
3,N1,NOYAPARA CULVERT,6.30,10.880,23.694391,90.537574,A
4,N1,ADUPUR CULVERT,6.30,10.897,23.694302,90.537707,A
5,N1,NAYABARI KASPUR BOX CULVERT,8.30,11.296,23.692360,90.540918,A
6,N1,KHAS PARA BOX CULVERT,9.30,12.239,23.688412,90.548559,A
7,N1,DAWAN BAG BOX CULVERT,6.10,12.253,23.688320,90.548650,A
8,N1,Madanpur Bridge.(L),27.50,12.660,23.685583,90.551208,A
9,N1,MADAN PUR (R),26.30,12.660,23.685583,90.551208,A
10,N1,MADANPUR BRIDGE(L),26.30,12.660,23.685583,90.551208,A
11,N1,Madanpur Bridge(R),27.50,12.688,23.685362,90.551359,A
12,N1,KAWTALA BOX CULVERT,11.90,13.574,23.677803,90.555819,A
13,N1,Darikandi Bridge (R),20.45,17.222,23.653972,90.577410,A
14,N1,Darikandi Bridge (L),20.50,17.222,23.653972,90.577410,A
15,N1,Sonakhal Bridge(L),25.50,18.093,23.649754,90.584549,A
16,N1,KRIBORDI BOX CULVERT,6.00,19.760,23.637954,90.593667,A
17,N1,Marikhali Bridge(L),86.92,21.184,23.628467,90.602302,A
18,N1,Marikhali Bridge(R),89.75,21.184,23.628467,90.602302,A
19,N1,MARIKHALL BRIDGE,89.20,21.184,23.628467,90.602302,A

In [ ]:
#van de bridges moeten we de dubbelen eruit filteren
#als (L) erin staat, extra kolom met gap BS, als er (R) staat, extra kolom met BS
#deze keuze maken we, dus die moeten we ook uitleggen


#een punt toevoegen tussen de